version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codesentinel-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - clickhouse
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: codesentinel-postgres
    environment:
      POSTGRES_DB: codesentinel
      POSTGRES_USER: codesentinel_user
      POSTGRES_PASSWORD: supersecurepassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: codesentinel-clickhouse
    ports:
      - "8123:8123"   # HTTP interface
      - "9000:9000"   # Native interface
    volumes:
      - chdata:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  pgdata:
  chdata:
